### ISSUE TITLE
尝试在RTX6000 48G显存机器上运行，出现OOM问题。运行这个项目需要多少显存？

### ISSUE THREAD

**Issue by SlothRan** [TemporaryLoRA/Temp-LoRA#2]
在运行“bash scripts/llama2.sh ”显式如下：
![image](https://github.com/TemporaryLoRA/Temp-LoRA/assets/61135297/08c9a0f1-527b-4471-af02-10665d246bca)
配置信息如下:
![image](https://github.com/TemporaryLoRA/Temp-LoRA/assets/61135297/749ab488-4771-4a0b-9111-ee3662e6f317)
![image](https://github.com/TemporaryLoRA/Temp-LoRA/assets/61135297/d8f1eb90-df17-4ec4-94d3-1f770ee019aa)
![image](https://github.com/TemporaryLoRA/Temp-LoRA/assets/61135297/0afd9a72-9714-4b57-aad2-722f69b4aecd)

**Comment by TemporaryLoRA** [comment]
刚重新做了测试，结果如下：
| script | enable gradient checkpointing | mem | 
| :-: | :-: | :-: |
| scripts/llama2.sh | True | 22GB | 
| scripts/llama2.sh | False | 56GB |
| scripts/example.sh | True | 24GB (step = 2) |
| scripts/example.sh | False | 36GB (step = 2) |

实验环境：A800, cuda11.8，mem由`nvidia-smi`命令得到。
实验配置为本项目提供的官方配置。

注意，"model.generate"过程中，transformers会自动进行一些显存的回收、释放，因此显存会有较大的波动。

启动`gradient_checkpointing`的方法，以`scripts/llama2.sh`为例，将最后的"--gradient_checkpointing" 设为 "true' 即可。
```bash
ACCELERATE_CONFIG=""
SAVE_DIR=""

MODEL_NAME="togethercomputer/LLaMA-2-7B-32K"

mkdir -p $SAVE_DIR
accelerate launch --config_file $ACCELERATE_CONFIG trainer/acc_pg19_trainer.py --model_name $MODEL_NAME \
  ……
  --gradient_checkpointing "true" 
```

麻烦您看下开启"gradient_checkpointing"后的结果。
